### ISSUE TITLE
setup travis 

### ISSUE THREAD

**Issue by ddomingof** [bio2bel/kegg#4]

**Comment by cthoyt** [comment]
isn't it already set up? Or did you want something changed?

**Comment by ddomingof** [comment]
nope tests are not passing... i think the confiruation is wrong because it complains about a module not being instlaled

**Comment by cthoyt** [comment]
I uploaded the hgnc and chebi packages, so the rest is up to you

**Comment by ddomingof** [comment]
Cool thanks
